#!/usr/bin/with-contenv bash

# Determine if setup is needed
if [ ! -f "/usr/bin/apt" ]; then
    echo "**** Image is not Ubuntu, skipping opencl-intel install ****"
    exit 0
fi

if ! dpkg -l | grep gnupg > /dev/null; then
    apt-get update && apt-get install -y gnupg
fi

if [ ! -f "/etc/apt/sources.list.d/kisak-mesa.list" ]; then
    echo "**** Adding kisak-mesa repo ****"
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F63F0F2B90935439
    source /etc/lsb-release
    echo "deb http://ppa.launchpad.net/kisak/kisak-mesa/ubuntu ${DISTRIB_CODENAME} main" > /etc/apt/sources.list.d/kisak-mesa.list
fi

if [ ! -f "/etc/apt/sources.list.d/rocm.list" ]; then
    echo "**** Adding rocm repo ****"
    wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | apt-key add -
    echo "deb [arch=amd64] https://repo.radeon.com/rocm/apt/4.5/ ubuntu main" > /etc/apt/sources.list.d/rocm.list
fi

pkgs='mesa-vdpau-drivers mesa-va-drivers mesa-vdpau-drivers libdrm-radeon1 rocm-opencl rocm-utils'

install=false
for pkg in $pkgs; do
    status="$(dpkg-query -W --showformat='${db:Status-Status}' "$pkg" 2>&1)"
    if [ ! $? = 0 ] || [ ! "$status" = installed ]; then
        install=true
        break
    fi
done

if "$install"; then
    echo "**** Adding mesa to package install list ****"
    echo "$pkgs" >> /mod-repo-packages-to-install.list
fi
