#!/usr/bin/with-contenv bash

if [ ! -f "/etc/apt/sources.list.d/rocm.list" ]; then
    echo "**** Adding rocm repo ****"
    wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | apt-key add -
    echo "deb [arch=amd64] https://repo.radeon.com/rocm/apt/4.5/ ubuntu main" > /etc/apt/sources.list.d/rocm.list
fi